#!/usr/bin/python3
import sys
import math

def get_nums(file):
    with open(file) as f:
        return [int(line.strip()) for line in f.readlines()]

def factorize(n):
    if n % 2 == 0:
        return [2] + factorize(n // 2)
    else:
        square_root = int(math.sqrt(n)) + 1
        for i in range(3, square_root, 2):
            if n % i == 0:
                return [i] + factorize(n // i)
            if n % (square_root - i) == 0:
                return [i, square_root - i] + factorize(n // (i + (square_root - i)))
            if n % (square_root + i) == 0:
                return [i, square_root + i] + factorize(n // (i + (square_root + i)))
        return [n]

def main():
    if len(sys.argv) != 2:
        print("Usage: factors.py <file>")
        sys.exit(1)
    nums = get_nums(sys.argv[1])
    for n in nums:
        factors = factorize(n)
        print("{} = {}".format(n, " * ".join(map(str, factors))))

if __name__ == "__main__":
    main(sys.argv[1:])