#!/usr/bin/python3
import sys
import math
"""Factorizes as many numbers as possible into a product of 2 smaller nums"""


def get_nums(file):
    """gets the numbers from file"""
    nums = []
    with open(file, encoding='utf-8') as f:
        for line in f.readlines():
            nums += int(line)
    return nums


def factorize(n):
    """factorize a number"""
    if n % 2 == 0:
        i = 2
        print("{}={}*{}".format(n, int(n//i), i))
    else:
        sqr = int(math.sqrt(num)) + 1
        for i in range(3, sqr, 2):
            if n % i == 0:
                print("{}={}*{}".format(n, int(n//i), i))
                return
            if n % (sqr + i) == 0:
                print("{}={}*{}".format(n, sqr + i, int(n//(sqr + i))))
                return
            if n % (sqr - i) == 0:
                print("{}={}*{}".format(n, sqr - 1, int(n//(sqr - i))))
                return


def main(args):
    """entry point"""
    if len(args) != 2:
        print("Usage: factors.py <file>")
        sys.exit(1)
    nums = get_nums(args[1])
    for n in nums:
        factorize(n)


if __name__ == "__main__":
    main(sys.argv[1:])
